FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=development

COPY package*.json ./

RUN npm ci

COPY tsconfig*.json nest-cli.json ./
COPY src ./src
COPY doc ./doc

EXPOSE 4000

CMD ["npm", "run", "start:dev"]
